import * as Icons from "heroicons-react";
import { signInUser } from "../../Utility/Auth";
import DatePicker from "react-datepicker";
import { useEffect, useState } from "react";
import { format } from "date-fns";
import WareHouseDW from "../../Common/CustomSelect/WareHouseDW";
import AlertService from "../../Utility/AlertService";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { useWarehouseQuery } from "../../../services/warehouseApi";
import SelectUsers from "../../Common/CustomSelect/SelectUsers";
import SelectProduct from "../../Common/CustomSelect/PosSearchProduct";
import SelectProductsReport from "../../Common/CustomSelect/SelectProductsReport";
// import { useOutOfStockProductsQuery } from "../../../services/reportsApi";

const OutOfStockProducts = () => {
  const auth = signInUser();
  // console.log("auth",auth)

  const [warehouse, setWarehouse] = useState("allWh");
  const [productId, setProductId] = useState();

  const [startDate, setStartDate] = useState(format(new Date(), "MM-dd-yyyy"));
  const [endDate, setEndDate] = useState(format(new Date(), "MM-dd-yyyy"));
  const { aamarId } = auth;
  // const lang = useSelector((state) => state.languageReducer);
  // const { data: salesData } = useOutOfStockProductsQuery({
  //   startDate,
  //   endDate,
  //   warehouse,
  //   aamarId,
  //   productId,
  // });
  let salesData = [];

  console.log(
    "Product wise Purchase data::>>",
    startDate,
    endDate,
    warehouse,
    aamarId,
    productId
  );

  console.log("purchase data", salesData);

  // fine warehouse Name
  const [whName, setWhName] = useState("All Warehouses");

  const { data: wh, refetch } = useWarehouseQuery(warehouse);

  // Call refetch only if user?.warehouse changes
  useEffect(() => {
    if (warehouse) {
      refetch();
    }
  }, [warehouse, refetch]);

  // Update warehouse name when data changes
  useEffect(() => {
    if (wh?.name) {
      setWhName(wh.name); // Directly set the name, no need for optional chaining here
    }
  }, [wh]);
  // console.log("Customer Wise Sales Report Data:", salesData);

  // Export CSV
  const handleExportCSV = () => {
    if (!salesData || salesData.length === 0) {
      AlertService.alert("Info", "No data available for export.");
      return;
    }

    const start = new Date(startDate).toLocaleDateString("en-US");
    const end = new Date(endDate).toLocaleDateString("en-US");
    const generatedOn = new Date().toLocaleString();
    const generatedBy = auth?.name || "Aamar Dokan";
    const storeName =
      auth?.storeSettings?.storeName?.toUpperCase() || "Aamar Dokan";
    const reportTitle = "Product Wise Purchase Report";

    // Header Info
    const headerInfo = [
      `Store: ${storeName},,,,,,,`,
      `Report: ${reportTitle},,,,,,,Date Range: ${start} to ${end}`,
      `Generated On: ${generatedOn},,,,,,,Generated By: ${generatedBy}`,
      "",
      "",
    ];

    // Table Headers
    const csvTableHeader = [
      "S/N",
      "Invoice No",
      "Warehouse",
      "Date",
      "Biller",
      "Total Items",
      "Discount",
      "Gross Total",
    ].join(",");

    // Totals
    let totalItems = 0;
    let totalDiscount = 0;
    let totalGross = 0;

    // Table Rows
    const csvRows = salesData.map((item, index) => {
      const items = Number(item.totalItem || 0);
      const discount = Number(item.discount || 0);
      const gross = Number(item.grossTotal || 0);

      totalItems += items;
      totalDiscount += discount;
      totalGross += gross;

      return [
        index + 1,
        item.invoiceId || "",
        item.warehouseName || "",
        new Date(item.date).toLocaleDateString("en-US"),
        item.billerName || "",
        items,
        discount.toFixed(2),
        gross.toFixed(2),
      ].join(",");
    });

    // Summary Footer
    const summaryLabelRow = [",,,,,,", "** SUMMARY **"].join(",");
    const summaryHeaderRow = [
      "",
      "",
      "",
      "",
      "",
      "Total Items",
      "Total Discount",
      "Total Gross",
    ].join(",");

    const summaryDataRow = [
      "",
      "",
      "",
      "",
      "",
      totalItems,
      totalDiscount.toFixed(2),
      totalGross.toFixed(2),
    ].join(",");

    // Combine all parts
    const csvContent = [
      ...headerInfo,
      csvTableHeader,
      ...csvRows,
      "",
      "",
      summaryLabelRow,
      summaryHeaderRow,
      summaryDataRow,
    ].join("\n");

    // Export logic
    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "OutOfStockProducts.csv";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };

  // export PDF
  const handleExportPDF = () => {
    if (!salesData || salesData.length === 0) {
      AlertService.alert("Info", "No data available for export.");
      return;
    }

    const doc = new jsPDF("landscape");

    const options = { month: "numeric", day: "numeric", year: "numeric" };
    const formattedStart = new Date(startDate).toLocaleDateString(
      "en-US",
      options
    );
    const formattedEnd = new Date(endDate).toLocaleDateString("en-US", options);
    const reportGeneratedAt = new Date().toLocaleString();

    const storeName =
      auth?.storeSettings?.storeName?.toUpperCase() || "Aamar Dokan";
    const reportName = "Biller Wise Sales Report";

    // Title
    doc.setFontSize(16);
    doc.text(storeName, 140, 15, { align: "center" });

    doc.setFontSize(12);
    doc.text(reportName, 140, 22, { align: "center" });

    // Header info
    doc.setFontSize(10);
    doc.text(`Store: ${storeName}`, 14, 28);
    doc.text(`Date: ${formattedStart} - ${formattedEnd}`, 14, 33);
    doc.text(`Generated At: ${reportGeneratedAt}`, 280, 28, { align: "right" });
    doc.text(`Generated By: ${auth?.name}`, 280, 33, { align: "right" });

    // Table headers
    const headers = [
      [
        "S/N",
        "Invoice No",
        "Warehouse",
        "Date",
        "Biller",
        "Total Item",
        "Discount",
        "Gross Total",
      ],
    ];

    const data = salesData.map((item, index) => [
      index + 1,
      item.invoiceId,
      item.warehouseName,
      new Date(item.date).toLocaleDateString("en-US"),
      item.billerName,
      item.totalItem,
      item.discount.toFixed(2),
      item.grossTotal.toFixed(2),
    ]);

    autoTable(doc, {
      head: headers,
      body: data,
      startY: 45,
      theme: "grid",
      styles: {
        fontSize: 9,
        halign: "center",
      },
      headStyles: {
        fillColor: [242, 101, 45],
        textColor: [255, 255, 255],
        fontStyle: "bold",
        lineWidth: 0.2,
        lineColor: [255, 255, 255],
      },
    });

    // === Summary Box ===
    const finalY = doc.lastAutoTable.finalY + 10;
    const lineHeight = 6;
    const boxHeight = 6 * lineHeight + 10;
    const boxWidth = 100;

    const pageWidth = doc.internal.pageSize.getWidth();
    const boxX = pageWidth - boxWidth - 15;
    const boxY = finalY;

    doc.setLineDashPattern([1, 1], 0);
    doc.rect(boxX, boxY, boxWidth, boxHeight);
    doc.setLineDashPattern([], 0);

    let y = boxY + 10;
    const labelX = boxX + 5;
    const valueX = boxX + boxWidth - 5;
    doc.setFontSize(9);

    const totalItems = sumField(salesData, "totalItem");
    const totalGross = sumField(salesData, "grossTotal");
    const totalDiscount = sumField(salesData, "discount");
    const totalNet = totalGross - totalDiscount;

    doc.text("Total Items :", labelX, y);
    doc.text(`${totalItems}`, valueX, y, { align: "right" });

    y += lineHeight;
    doc.text("Total Gross Amount :", labelX, y);
    doc.text(`${totalGross}`, valueX, y, { align: "right" });

    y += lineHeight;
    doc.text("Total Discount :", labelX, y);
    doc.text(`${totalDiscount}`, valueX, y, { align: "right" });

    y += lineHeight;
    doc.text("Total Net Amount :", labelX, y);
    doc.text(`${totalNet}`, valueX, y, { align: "right" });

    doc.save("OutOfStockProducts.pdf");
  };

  // Utility to sum values from objects
  const sumField = (data, field) =>
    data
      ?.reduce((acc, item) => acc + (parseFloat(item[field]) || 0), 0)
      .toFixed(2);

  //warehouse
  const handleOnchangeWareHouseFrom = (e) => {
    if (e.option !== "no-warehouse") {
      setWarehouse(e.option);
    } else {
      setWarehouse("allWh");
    }
  };

  return (
    <div>
      {/* <div>
        <h2 className="mb-3">
          <Icons.ShoppingCartOutline size={35} /> Product Wise Sales Report
        </h2>
      </div> */}

      <div
        style={{
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          minHeight: "300px",
          marginTop: "40px",
        }}
      >
        <h2
          style={{
            color: "#F2652D",
            fontWeight: 700,
            fontSize: 32,
            marginBottom: 8,
          }}
        >
          Coming Soon
        </h2>
        <p
          style={{
            color: "#555",
            fontSize: 18,
            maxWidth: 400,
            textAlign: "center",
          }}
        >
          This report will be available very soon. Thank you for your patience!
        </p>
      </div>
    </div>
  );
};

export default OutOfStockProducts;
