import * as Icons from "heroicons-react";
import { signInUser } from "../../Utility/Auth";
import DatePicker from "react-datepicker";
import { useEffect, useState } from "react";
import { format } from "date-fns";
import WareHouseDW from "../../Common/CustomSelect/WareHouseDW";
import AlertService from "../../Utility/AlertService";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { useWarehouseQuery } from "../../../services/warehouseApi";
import SelectUsers from "../../Common/CustomSelect/SelectUsers";
import SelectProduct from "../../Common/CustomSelect/PosSearchProduct";
import SelectProductsReport from "../../Common/CustomSelect/SelectProductsReport";
import { useProductWisePurchaseQuery } from "../../../services/reportsApi";

const ProductWisePurchase = () => {
  const auth = signInUser();
  // console.log("auth",auth)

  const [warehouse, setWarehouse] = useState("allWh");
  const [productId, setProductId] = useState();

  const [startDate, setStartDate] = useState(format(new Date(), "MM-dd-yyyy"));
  const [endDate, setEndDate] = useState(format(new Date(), "MM-dd-yyyy"));
  const { aamarId } = auth;
  // const lang = useSelector((state) => state.languageReducer);
  const { data: grnData } = useProductWisePurchaseQuery({
    startDate,
    endDate,
    warehouse,
    aamarId,
    productId,
  });

  console.log("Product wise Purchase data::>>", startDate,
    endDate,
    warehouse,
    aamarId,
    productId);

  console.log('purchase data', grnData)

  // fine warehouse Name
  const [whName, setWhName] = useState("All Warehouses");

  const { data: wh, refetch } = useWarehouseQuery(warehouse);

  // Call refetch only if user?.warehouse changes
  useEffect(() => {
    if (warehouse) {
      refetch();
    }
  }, [warehouse, refetch]);

  // Update warehouse name when data changes
  useEffect(() => {
    if (wh?.name) {
      setWhName(wh.name); // Directly set the name, no need for optional chaining here
    }
  }, [wh]);
  // console.log("Customer Wise Sales Report Data:", grnData);

  // Export CSV
  const handleExportCSV = () => {


    if (!grnData || grnData?.length === 0) {
      AlertService.alert("Info", "No data available for export.");
      return;
    }

    const start = new Date().toLocaleDateString("en-US");
    const end = new Date().toLocaleDateString("en-US");
    const generatedOn = new Date().toLocaleString();
    const generatedBy = auth?.name || "Aamar Dokan";
    const storeName =
      auth?.storeSettings?.storeName?.toUpperCase() || "Aamar Dokan";
    const reportTitle = "Product Wise Purchase Report";

    const headerInfo = [
      `Store: ${storeName},,,,,,,,,,,,,`,
      `Report: ${reportTitle},,,,,,,,,,,,,Date Range: ${start} to ${end}`,
      `Generated On: ${generatedOn},,,,,,,,,,,,,Generated By: ${generatedBy}`,
      "",
      "",
    ];

    const csvTableHeader = [
      "S/N",
      "GRN No",
      "PO No",
      "TPN No",
      "Date",
      "Supplier",
      "Product Name",
      "Warehouse",
      "Article Code",
      "Trade Price",
      "Qty",
      "Amount",
    ].join(",");

    let totalQty = 0;
    let totalAmount = 0;

    const csvRows = grnData.map((item, index) => {
      totalQty += Number(item.qty || 0);
      totalAmount += Number(item.amount || 0);

      return [
        index + 1,
        item.grnNo || "",
        item.poNo || "",
        item.tpnNo || "",
        new Date(item.date).toLocaleDateString("en-US"),
        item.supplierName || "",
        item.productName || "",
        item.warehouse || "",
        item.article_code || "",
        item.tp || 0,
        item.qty || 0,
        item.amount || 0,
      ].join(",");
    });

    const summaryLabelRow = [",,,,,,,,,,", "** SUMMARY **"].join(",");
    const summaryHeaderRow = [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Total Qty",
      "Total Amount",
    ].join(",");

    const summaryDataRow = [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      totalQty,
      totalAmount.toFixed(2),
    ].join(",");

    const csvContent = [
      ...headerInfo,
      csvTableHeader,
      ...csvRows,
      "",
      "",
      summaryLabelRow,
      summaryHeaderRow,
      summaryDataRow,
    ].join("\n");

    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "ProductWisePurchase.csv";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };


  // export PDF
  const handleExportPDF = () => {

    if (!grnData || grnData?.length === 0) {
      AlertService.alert("Info", "No GRN data available for export.");
      return;
    }

    const doc = new jsPDF("landscape");

    const options = { month: "numeric", day: "numeric", year: "numeric" };
    const formattedStart = new Date(grnData[0].date).toLocaleDateString("en-US", options);
    const formattedEnd = formattedStart;
    const reportGeneratedAt = new Date().toLocaleString();

    const storeName = auth?.storeSettings?.storeName?.toUpperCase() || "Aamar Dokan";
    const reportName = "Product Wise Purchase Report";

    // Title
    doc.setFontSize(16);
    doc.text(storeName, 140, 15, { align: "center" });

    doc.setFontSize(12);
    doc.text(reportName, 140, 22, { align: "center" });

    // Header Info
    doc.setFontSize(10);
    doc.text(`Store: ${storeName}`, 14, 28);
    doc.text(`Date: ${formattedStart} - ${formattedEnd}`, 14, 33);
    doc.text(`Generated At: ${reportGeneratedAt}`, 280, 28, { align: "right" });
    doc.text(`Generated By: ${auth?.name || "System"}`, 280, 33, { align: "right" });

    // Table Headers
    const headers = [[
      "S/N", "GRN No", "PO No", "TPN No", "Date", "Supplier",
      "Product", "Article Code", "Warehouse", "TP", "Qty", "Amount"
    ]];

    const data = grnData.map((item, index) => [
      index + 1,
      item.grnNo,
      item.poNo,
      item.tpnNo,
      new Date(item.date).toLocaleDateString("en-US"),
      item.supplierName,
      item.productName,
      item.article_code,
      item.warehouse,
      item.tp.toFixed(2),
      item.qty,
      item.amount.toFixed(2),
    ]);

    autoTable(doc, {
      head: headers,
      body: data,
      startY: 45,
      theme: "grid",
      styles: {
        fontSize: 9,
        halign: "center",
      },
      headStyles: {
        fillColor: [242, 101, 45],
        textColor: [255, 255, 255],
        fontStyle: "bold",
        lineWidth: 0.2,
        lineColor: [255, 255, 255],
      },
    });

    // Summary Box
    const finalY = doc.lastAutoTable.finalY + 10;
    const lineHeight = 6;
    const boxHeight = 4 * lineHeight + 10;
    const boxWidth = 100;

    const pageWidth = doc.internal.pageSize.getWidth();
    const boxX = pageWidth - boxWidth - 15;
    const boxY = finalY;

    doc.setLineDashPattern([1, 1], 0);
    doc.rect(boxX, boxY, boxWidth, boxHeight);
    doc.setLineDashPattern([], 0);

    let y = boxY + 10;
    const labelX = boxX + 5;
    const valueX = boxX + boxWidth - 5;
    doc.setFontSize(9);

    const totalQty = grnData.reduce((sum, item) => sum + item.qty, 0);
    const totalAmount = grnData.reduce((sum, item) => sum + item.amount, 0);

    doc.text("Total Quantity :", labelX, y);
    doc.text(`${totalQty}`, valueX, y, { align: "right" });

    y += lineHeight;
    doc.text("Total Amount :", labelX, y);
    doc.text(`${totalAmount.toFixed(2)}`, valueX, y, { align: "right" });

    doc.save("ProductWisePurchase.pdf");
  };


  // Utility to sum values from objects
  const sumField = (data, field) =>
    data
      ?.reduce((acc, item) => acc + (parseFloat(item[field]) || 0), 0)
      .toFixed(2);

  //warehouse
  const handleOnchangeWareHouseFrom = (e) => {
    if (e.option !== "no-warehouse") {
      setWarehouse(e.option);
    } else {
      setWarehouse("allWh");
    }
  };

  return (
    <div>
      <div>
        <h2 className="mb-3">
          <Icons.ShoppingCartOutline size={35} /> Product Wise Purchase Report
        </h2>
      </div>

      <div
        className="mt-3 w-40 p-3"
        style={{ backgroundColor: "#f1f3f5", borderRadius: "8px" }}
      >
        <div className="d-flex mt-2 mb-2 align-items-center justify-content-center gap-2">
          <DatePicker
            selected={new Date(startDate)}
            className="form-control w-100"
            onChange={(date) =>
              setStartDate(format(new Date(date), "MM-dd-yyyy"))
            }
          />
          <DatePicker
            selected={new Date(endDate)}
            className="form-control me-4"
            onChange={(date) =>
              setEndDate(format(new Date(date), "MM-dd-yyyy"))
            }
          />
        </div>

        <div className="">
          {auth?.type === "admin" && (
            <div className="my-3">
              <WareHouseDW
                id="warehouse"
                name="warehouse"
                handleOnChange={handleOnchangeWareHouseFrom}
                className="form-control"
              />
            </div>
          )}
          <SelectProductsReport
            onProductSelect={({ id, article_code }) => {
              console.log("Selected Product ID:", id);
              // console.log("Selected Article Code:", article_code);
              setProductId(id);
              // setProductId(article_code); // Only if you need to store/use it
            }}
          />
        </div>

        <div className="d-flex gap-3 justify-content-center align-items-center text-center">
          <button
            className="btn btn-dark w-100 mt-3"
            style={{ borderRadius: "5px" }}
            onClick={handleExportCSV}
          >
            <Icons.DownloadOutline size={22} /> Download CSV
          </button>

          <button
            className="btn btn-dark w-100 mt-3"
            style={{ borderRadius: "5px" }}
            onClick={handleExportPDF}
          >
            <Icons.DocumentOutline size={22} /> Download PDF
          </button>
        </div>
      </div>
    </div>
  );
};

export default ProductWisePurchase;
