import * as Icons from "heroicons-react";
import { signInUser } from "../../Utility/Auth";
import DatePicker from "react-datepicker";
import { useEffect, useState } from "react";
import { format } from "date-fns";
import WareHouseDW from "../../Common/CustomSelect/WareHouseDW";
import AlertService from "../../Utility/AlertService";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { useCustomerWiseSalesQuery } from "../../../services/reportsApi";
import SelectCustomerReport from "../../Common/CustomSelect/SelectCustomerReport";
import { useWarehouseQuery } from "../../../services/warehouseApi";

const CustomerWiseSalesReport = () => {
  const auth = signInUser();
  // console.log("auth",auth)

  const [warehouse, setWarehouse] = useState("allWh");
  const [customerId, setCustomerId] = useState();

  const [startDate, setStartDate] = useState(format(new Date(), "MM-dd-yyyy"));
  const [endDate, setEndDate] = useState(format(new Date(), "MM-dd-yyyy"));
  const { aamarId } = auth;
  // const lang = useSelector((state) => state.languageReducer);
  const { data: salesData } = useCustomerWiseSalesQuery({
    startDate,
    endDate,
    warehouse,
    aamarId,
    customerId,
  });

  // fine warehouse Name
  const [whName, setWhName] = useState("All Warehouses");

  const { data: wh, refetch } = useWarehouseQuery(warehouse, {
    skip: warehouse === "allWh",
  });


  // Update warehouse name when data changes (handled automatically by RTK Query refetch on arg change)
  useEffect(() => {
    if (wh?.name) {
      setWhName(wh.name);
    }
  }, [wh]);
  // console.log("Customer Wise Sales Report Data:", salesData);

  // Export CSV
  const handleExportCSV = () => {
    if (salesData.length === 0) {
      AlertService.alert("Info", "No data available for export");
      return;
    }

    const start = new Date(startDate).toLocaleDateString("en-US");
    const end = new Date(endDate).toLocaleDateString("en-US");
    const generatedOn = new Date().toLocaleString();
    const generatedBy = auth?.name || "Aamar Dokan";
    const storeName = auth?.storeSettings?.storeName?.toUpperCase() || "Aamar Dokan";
    const warehouseName = whName;
    const reportTitle = "Customer Wise Sales Report";

    // Header Info
    const headerInfo = [
      `Store: ${storeName},,,,,,,Warehouse: ${warehouseName}`,
      `Report: ${reportTitle},,,,,,,Date Range: ${start} to ${end}`,
      `Generated On: ${generatedOn},,,,,,,Generated By: ${generatedBy}`,
      "", "", // Empty rows for spacing
    ];

    // Table Headers
    const csvTableHeader = [
      "S/N",
      "Invoice No",
      "Date",
      "Customer Name",
      "Phone",
      "Membership",
      "Total Items",
      "Gross Total",
      "Discount",
      "Total",
      "Received",
      "Change",
    ].join(",");

    // Totals
    let totalItems = 0;
    let totalGross = 0;
    let totalDiscount = 0;
    let totalAmount = 0;
    let totalReceived = 0;
    let totalChange = 0;

    // Table Rows
    const csvRows = salesData.map((row, index) => {
      const items = Number(row.totalItem || 0);
      const gross = Number(row.grossTotal || 0);
      const discount = Number(row.promoDiscount || 0);
      const total = Number(row.total || 0);
      const received = Number(row.totalReceived || 0);
      const change = Number(row.changeAmount || 0);

      totalItems += items;
      totalGross += gross;
      totalDiscount += discount;
      totalAmount += total;
      totalReceived += received;
      totalChange += change;

      return [
        index + 1,
        row.invoiceNo || "",
        row.createdAt || "",
        row.customerName || "",
        row.customerPhone || "",
        row.customerMembership || "N/A",
        items,
        gross.toFixed(2),
        discount.toFixed(2),
        total.toFixed(2),
        received.toFixed(2),
        change.toFixed(2),
      ].join(",");
    });

    // Summary Footer
    const summaryLabelRow = [",,,,,,,", "** SUMMARY **"].join(",");
    const summaryHeaderRow = [
      "",
      "",
      "",
      "",
      "",
      "",
      "Total Items",
      "Gross Total",
      "Discount",
      "Total",
      "Received",
      "Change",
    ].join(",");

    const summaryDataRow = [
      "",
      "",
      "",
      "",
      "",
      "",
      totalItems,
      totalGross.toFixed(2),
      totalDiscount.toFixed(2),
      totalAmount.toFixed(2),
      totalReceived.toFixed(2),
      totalChange.toFixed(2),
    ].join(",");

    // Combine all parts
    const csvContent = [
      ...headerInfo,
      csvTableHeader,
      ...csvRows,
      "", "", "",
      summaryLabelRow,
      summaryHeaderRow,
      summaryDataRow,
    ].join("\n");

    // Export logic
    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "CustomerWiseSalesReport.csv";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };


  // export PDF
  const handleExportPDF = () => {
    if (!salesData || salesData?.length === 0) {
      AlertService.alert("Info", "No data available for export.");
      return;
    }

    const doc = new jsPDF("landscape");

    const options = { month: "numeric", day: "numeric", year: "numeric" };
    const formattedStart = new Date(startDate).toLocaleDateString(
      "en-US",
      options
    );
    const formattedEnd = new Date(endDate).toLocaleDateString("en-US", options);
    const reportGeneratedAt = new Date().toLocaleString();

    const storeName =
      auth?.storeSettings?.storeName?.toUpperCase() || "Aamar Dokan";
    const warehouseName = whName;
    const reportName = "Customer Wise Sales Report";

    // Title
    doc.setFontSize(16);
    doc.text(storeName, 140, 15, { align: "center" });

    doc.setFontSize(12);
    doc.text(reportName, 140, 22, { align: "center" });

    // Header info - Justify between
    doc.setFontSize(10);
    doc.text(`Store: ${storeName}`, 14, 28);
    doc.text(`Warehouse: ${warehouseName}`, 14, 33);
    doc.text(`Date: ${formattedStart} - ${formattedEnd}`, 14, 39);
    // doc.text(`Report: ${reportName}`, 140, 28, { align: "center" });
    doc.text(`Generated At: ${reportGeneratedAt}`, 280, 28, { align: "right" });
    doc.text(`Generated By: ${auth?.name}`, 280, 33, { align: "right" });

    // Table header
    const headers = [
      [
        "S/N",
        "Invoice No",
        "Date",
        "Customer Name",
        "Phone",
        "Membership",
        "Total Items",
        "Gross Total",
        "Discount",
        "Total",
        "Received",
        "Change",
      ],
    ];

    const data = salesData?.map((item, index) => [
      index + 1,
      item.invoiceNo || "",
      item.createdAt || "",
      item.customerName || "",
      item.customerPhone || "",
      item.customerMembership || "",
      item.totalItem || 0,
      (item.grossTotal || 0).toFixed(2),
      (item.promoDiscount || 0).toFixed(2),
      (item.total || 0).toFixed(2),
      (item.totalReceived || 0).toFixed(2),
      (item.changeAmount || 0).toFixed(2),
    ]);

    autoTable(doc, {
      head: headers,
      body: data,
      startY: 45,
      theme: "grid",
      styles: {
        fontSize: 9,
        halign: "center",
      },
      headStyles: {
        fillColor: [242, 101, 45], // tomato background
        textColor: [255, 255, 255], // white text
        fontStyle: "bold",
        lineWidth: 0.2, // line thickness
        lineColor: [255, 255, 255], // white border color
      },
    });

    // === Summary Box ===
    const finalY = doc.lastAutoTable.finalY + 20;
    const lineHeight = 6; // smaller line height
    const numberOfRows = 7;
    const extraLineHeight = 1.5;
    const boxHeight =
      numberOfRows * lineHeight + extraLineHeight * lineHeight + 10;
    const boxWidth = 100; // smaller width

    // Position it to the right side
    const pageWidth = doc.internal.pageSize.getWidth();
    const boxX = pageWidth - boxWidth - 15;
    const boxY = finalY;

    // Draw dotted border
    doc.setLineDashPattern([1, 1], 0);
    doc.rect(boxX, boxY, boxWidth, boxHeight);
    doc.setLineDashPattern([], 0); // reset to solid

    let y = boxY + 10;
    const labelX = boxX + 5;
    const valueX = boxX + boxWidth - 5;
    doc.setFontSize(9);

    // Calculations
    const totalGross = sumField(salesData, "grossTotal");
    // const totalDiscount = sumField(salesData, "promoDiscount");
    const totalAmount = sumField(salesData, "total");
    // const totalReceived = sumField(salesData, "totalReceived");
    const totalItem = sumField(salesData, "totalItem");

    const gpAmount = (totalAmount - totalGross).toFixed(2);
    const gpPercent = ((gpAmount / totalGross) * 100).toFixed(2);

    // Row 1: Total Items
    doc.text("Total Items :", labelX, y);
    doc.text(`${totalItem}`, valueX, y, { align: "right" });

    // Spacing Gap
    y += lineHeight + 3;

    // Row 2: Total Cost Amount
    doc.text("Total Cost Amount :", labelX, y);
    doc.text(`${totalGross}`, valueX, y, { align: "right" });

    // Row 3: Total Net Amount
    y += lineHeight;
    doc.text("Total Net Amount :", labelX, y);
    doc.text(`${totalAmount}`, valueX, y, { align: "right" });

    // Spacing Gap
    y += lineHeight + 3;

    // Row 4: Return Adjusted Message
    doc.setTextColor(242, 101, 45);
    doc.setFont(undefined, "bold");
    doc.text("** Return Adjusted **", boxX + boxWidth / 2, y, {
      align: "center",
    });
    doc.setTextColor(0, 0, 0);
    doc.setFont(undefined, "normal");

    // Spacing Gap
    y += lineHeight + 3;

    // Row 5: GP Amount
    doc.text("GP Amount :", labelX, y);
    doc.text(`${gpAmount}`, valueX, y, { align: "right" });

    // Row 6: GP %
    y += lineHeight;
    doc.text("GP % :", labelX, y);
    doc.text(`${gpPercent}%`, valueX, y, { align: "right" });

    // Save the PDF
    doc.save("SalesSummary.pdf");
  };

  // Utility to sum values from objects
  const sumField = (data, field) =>
    data
      ?.reduce((acc, item) => acc + (parseFloat(item[field]) || 0), 0)
      .toFixed(2);

  //warehouse
  const handleOnchangeWareHouseFrom = (e) => {
    if (e.option !== "no-warehouse") {
      setWarehouse(e.option);
    } else {
      setWarehouse("allWh");
    }
  };

  return (
    <div>
      <div>
        <h2 className="mb-3">
          <Icons.ShoppingCartOutline size={35} /> Customer Wise Sales Report
        </h2>
      </div>

      <div
        className="mt-3 w-40 p-3"
        style={{ backgroundColor: "#f1f3f5", borderRadius: "8px" }}
      >
        <div className="d-flex mt-2 mb-2 align-items-center justify-content-center gap-2">
          <DatePicker
            selected={new Date(startDate)}
            className="form-control w-100"
            onChange={(date) =>
              setStartDate(format(new Date(date), "MM-dd-yyyy"))
            }
          />
          <DatePicker
            selected={new Date(endDate)}
            className="form-control me-4"
            onChange={(date) =>
              setEndDate(format(new Date(date), "MM-dd-yyyy"))
            }
          />
        </div>

        <div className="">
          {auth?.type === "admin" && (
            <div className="my-3">
              <WareHouseDW
                id="warehouse"
                name="warehouse"
                handleOnChange={handleOnchangeWareHouseFrom}
                className="form-control"
              />
            </div>
          )}
          <SelectCustomerReport
            aamarId={aamarId}
            onCustomerSelect={(id) => {
              setCustomerId(id); // This function will receive the selected customerId
            }}
          />
        </div>

        <div className="d-flex gap-3 justify-content-center align-items-center text-center">
          <button
            className="btn btn-dark w-100 mt-3"
            style={{ borderRadius: "5px" }}
            onClick={handleExportCSV}
          >
            <Icons.DownloadOutline size={22} /> Download CSV
          </button>

          <button
            className="btn btn-dark w-100 mt-3"
            style={{ borderRadius: "5px" }}
            onClick={handleExportPDF}
          >
            <Icons.DocumentOutline size={22} /> Download PDF
          </button>
        </div>
      </div>
    </div>
  );
};

export default CustomerWiseSalesReport;
