import * as Icons from "heroicons-react";
import { signInUser } from "../../Utility/Auth";
import DatePicker from "react-datepicker";
import { useEffect, useState } from "react";
import { format } from "date-fns";
import WareHouseDW from "../../Common/CustomSelect/WareHouseDW";
import AlertService from "../../Utility/AlertService";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { useSupplierWiseSalesQuery } from "../../../services/reportsApi";
import SelectSupplier from "../../Common/CustomSelect/SelectSupplier";
import { useWarehouseQuery } from "../../../services/warehouseApi";

const SupplierWiseSales = () => {
  const auth = signInUser();

  const [warehouse, setWarehouse] = useState("allWh");
  const [supplierId, setSupplierId] = useState();

  const [startDate, setStartDate] = useState(format(new Date(), "MM-dd-yyyy"));
  const [endDate, setEndDate] = useState(format(new Date(), "MM-dd-yyyy"));
  const { aamarId } = auth;

  const { data: salesData } = useSupplierWiseSalesQuery(
    {
      startDate,
      endDate,
      warehouse,
      aamarId,
      supplierId,
    },
    {
      skip: !supplierId,
    }
  );

  const [whName, setWhName] = useState("All Warehouses");
  const { data: wh, refetch } = useWarehouseQuery(warehouse);

  useEffect(() => {
    if (warehouse) {
      refetch();
    }
  }, [warehouse, refetch]);

  useEffect(() => {
    if (wh?.name) {
      setWhName(wh.name);
    } else {
      setWhName("All Warehouses");
    }
  }, [wh, warehouse]);

  const handleExportCSV = () => {
    if (!salesData || salesData.length === 0) {
      AlertService.alert("Info", "No data available for export");
      return;
    }

    const start = new Date(startDate).toLocaleDateString("en-US");
    const end = new Date(endDate).toLocaleDateString("en-US");
    const generatedOn = new Date().toLocaleString();
    const generatedBy = auth?.name || "Aamar Dokan";
    const storeName = auth?.storeSettings?.storeName?.toUpperCase() || "Aamar Dokan";
    const reportTitle = "Supplier Wise Sales Report";

    const headerInfo = [
      `Store: ${storeName},,,,,,,`,
      `Report: ${reportTitle},,,,,,,Date Range: ${start} to ${end}`,
      `Generated On: ${generatedOn},,,,,,,Generated By: ${generatedBy}`,
      "", ""
    ];

    const csvHeader = [
      "S/N",
      "Invoice No",
      "Date",
      "Product Name",
      "Article Code",
      "Warehouse",
      "Qty",
      "TP",
      "MRP",
      "Amount",
      "Profit",
    ].join(",");

    const csvRows = salesData.map((row, index) => {
      return [
        index + 1,
        row.invoiceId || "",
        format(new Date(row.date), "dd/MM/yyyy"),
        `"${row.productName}"`,
        row.articleCode || "",
        row.warehouseName || "",
        row.qty,
        row.tp.toFixed(2),
        row.mrp.toFixed(2),
        row.amount.toFixed(2),
        row.profit.toFixed(2),
      ].join(",");
    });

    const csvContent = [...headerInfo, csvHeader, ...csvRows].join("\n");
    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `SupplierWiseSales_${format(new Date(), "yyyyMMdd")}.csv`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };

  const handleExportPDF = () => {
    if (!salesData || salesData.length === 0) {
      AlertService.alert("Info", "No data available for export.");
      return;
    }

    const doc = new jsPDF("landscape");
    const storeName = auth?.storeSettings?.storeName?.toUpperCase() || "Aamar Dokan";
    const reportName = "Supplier Wise Sales Report";

    const options = { month: "numeric", day: "numeric", year: "numeric" };
    const formattedStart = new Date(startDate).toLocaleDateString("en-US", options);
    const formattedEnd = new Date(endDate).toLocaleDateString("en-US", options);
    const reportGeneratedAt = new Date().toLocaleString();

    doc.setFontSize(16);
    doc.text(storeName, 140, 15, { align: "center" });
    doc.setFontSize(12);
    doc.text(reportName, 140, 22, { align: "center" });

    doc.setFontSize(10);
    doc.text(`Store: ${storeName}`, 14, 28);
    doc.text(`Date: ${formattedStart} - ${formattedEnd}`, 14, 33);
    doc.text(`Generated At: ${reportGeneratedAt}`, 280, 28, { align: "right" });
    doc.text(`Generated By: ${auth?.name}`, 280, 33, { align: "right" });

    const headers = [
      ["S/N", "Invoice No", "Date", "Product Name", "Article Code", "Warehouse", "Qty", "TP", "MRP", "Amount", "Profit"],
    ];

    const data = salesData.map((item, index) => [
      index + 1,
      item.invoiceId || "",
      format(new Date(item.date), "dd/MM/yyyy"),
      item.productName,
      item.articleCode,
      item.warehouseName,
      item.qty,
      item.tp.toFixed(2),
      item.mrp.toFixed(2),
      item.amount.toFixed(2),
      item.profit.toFixed(2),
    ]);

    autoTable(doc, {
      head: headers,
      body: data,
      startY: 45,
      theme: "grid",
      styles: { fontSize: 8, halign: "center" },
      headStyles: { 
        fillColor: [242, 101, 45], 
        textColor: [255, 255, 255],
        fontStyle: "bold",
        lineWidth: 0.2,
        lineColor: [255, 255, 255],
      },
    });

    // === Summary Box ===
    const finalY = doc.lastAutoTable.finalY + 10;
    const lineHeight = 6;
    const boxHeight = 5 * lineHeight + 10;
    const boxWidth = 100;

    const pageWidth = doc.internal.pageSize.getWidth();
    const boxX = pageWidth - boxWidth - 15;
    const boxY = finalY;

    doc.setLineDashPattern([1, 1], 0);
    doc.rect(boxX, boxY, boxWidth, boxHeight);
    doc.setLineDashPattern([], 0);

    let y = boxY + 10;
    const labelX = boxX + 5;
    const valueX = boxX + boxWidth - 5;
    doc.setFontSize(9);

    const totalQty = sumField(salesData, "qty");
    const totalAmount = sumField(salesData, "amount");
    const totalProfit = sumField(salesData, "profit");

    doc.text("Total Items :", labelX, y);
    doc.text(`${totalQty}`, valueX, y, { align: "right" });

    y += lineHeight;
    doc.text("Total Sales Amount :", labelX, y);
    doc.text(`${totalAmount}`, valueX, y, { align: "right" });

    y += lineHeight;
    doc.text("Total Profit :", labelX, y);
    doc.text(`${totalProfit}`, valueX, y, { align: "right" });

    doc.save("SupplierWiseSales.pdf");
  };

  const sumField = (data, field) =>
    data?.reduce((acc, item) => acc + (parseFloat(item[field]) || 0), 0).toFixed(2);

  const handleOnchangeWareHouseFrom = (e) => {
    if (e.option !== "no-warehouse") {
      setWarehouse(e.option);
    } else {
      setWarehouse("allWh");
    }
  };

  return (
    <div>
      <div>
        <h2 className="mb-3">
          <Icons.ShoppingCartOutline size={35} /> Supplier Wise Sales Report
        </h2>
      </div>

      <div
        className="mt-3 w-40 p-3"
        style={{ backgroundColor: "#f1f3f5", borderRadius: "8px" }}
      >
        <div className="d-flex mt-2 mb-2 align-items-center justify-content-center gap-2">
          <DatePicker
            selected={new Date(startDate)}
            className="form-control w-100"
            onChange={(date) =>
              setStartDate(format(new Date(date), "MM-dd-yyyy"))
            }
          />
          <DatePicker
            selected={new Date(endDate)}
            className="form-control me-4"
            onChange={(date) =>
              setEndDate(format(new Date(date), "MM-dd-yyyy"))
            }
          />
        </div>

        <div className="">
          {auth?.type === "admin" && (
            <div className="my-3">
              <WareHouseDW
                id="warehouse"
                name="warehouse"
                handleOnChange={handleOnchangeWareHouseFrom}
                className="form-control"
              />
            </div>
          )}
          <SelectSupplier
            handleOnchange={(e) => {
              setSupplierId(e?.option);
            }}
          />
        </div>

        <div className="d-flex gap-3 justify-content-center align-items-center text-center">
          <button
            className="btn btn-dark w-100 mt-3"
            style={{ borderRadius: "5px" }}
            onClick={handleExportCSV}
          >
            <Icons.DownloadOutline size={22} /> Download CSV
          </button>

          <button
            className="btn btn-dark w-100 mt-3"
            style={{ borderRadius: "5px" }}
            onClick={handleExportPDF}
          >
            <Icons.DocumentOutline size={22} /> Download PDF
          </button>
        </div>
      </div>
    </div>
  );
};

export default SupplierWiseSales;
