export interface Account {
    _id: string,
    supplier: string,
    paidAmount: any,
    paidTo: string,
    photo: string,
    accountHead: string,
    user: string,
    date: string,
    amount: string,
    due: string,
    type: string,
    paymentType: string,
    paymentMethodType: string,
    grnId: string,
    poId: string,
    note: string,
    status: string,
}