export interface Product {
    "_id": string,
    "name": string,
    "ean": string,
    "article_code": string,
    "master_category": string,
    "category": string,
    "subCategory": string,
    "product_type": string,
    "priceList": any,
    "brand": string,
    "slug": string,
    "details": string,
    "unit": string,
    "alert_quantity": Number,
    "vat": Number,
    "vat_method": Boolean,
    "featured": Boolean,
    "shipping_method": string,
    "hide_website": Boolean,
    "promo_price": string,
    "promo_start": Date,
    "promo_end": Date,
    "specification": string,
    "photo": string,
    "status": string,
}